# Generated by Django 4.2.5 on 2023-09-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap1', '0002_category_location_trip_post_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='upload/%Y/%m'),
        ),
    ]
